#EpicFactions Plugin
#Created by Justin Brubaker aka JustBru00
#
#       ----------DISCLAIMER----------
#   This plugin messages the plugin developer 
#   if he joins the server.
#       ----------DISCLAIMER----------
#
#Plugin idea created by Hayden L. aka ComputerDude

#Commands
commands:
    #/epicfactions command
    epicfactions: 
        #Permission for the command
        permission: 'epicfactions.epicfactions'
    
    #/xpbottle command
    xpbottle:
        #Permission for the command
        permission: ''
        
#Editable Plugin Messages       
messages:
    #Plugin prefix before all msgs
    prefix: ''
    
    epicfactions:
        noperms: '&cYou don''t have permission to use that command.'        
        status: ''
        version: ''
        argserror: '&cPlease type "license", "version", or "status"'
    
    xpbottle:
        noperms: ''
        notenoughlvls: ''
        success: ''