#EpicFactions Plugin
#Created by Justin Brubaker aka JustBru00
#
#       ----------DISCLAIMER----------
#   This plugin messages the plugin developer 
#   if he joins the server.
#       ----------DISCLAIMER----------
#
#Plugin idea by Hayden L. aka ComputerDude

#Commands
commands:
    #/epicfactions command
    epicfactions: 
        #Permission for the command
        permission: 'epicfactions.epicfactions'
    
    #/xpbottle command
    bottlexp:
        #Permission for the command
        permission: 'epicfactions.bottlexp'
        
#Editable Plugin Messages       
messages:
    #Plugin prefix before all msgs
    prefix: '&8[&bEpic&fFactions&8] &f'
    
    epicfactions:
        noperms: '&cYou don''t have permission to use that command.'        
        status: ''
        version: '&fPlugin Version is %version%.'
        argserror: '&cPlease type "license", "version", or "status"'
    
    bottlexp:
        noperms: '&cYou don''t have permission to use this command.'
        notenoughlvls: '&cYou don''t have enough levels.'
        success: '&aYou were given a XP Bottle.'
        invalidnumber: '&cYou must type a number after /bottlexp' 
        argserror: '&cYou must type only one number after /bottlexp'
        invalidsender: '&cYou can''t use this command. (Sorry console)'