name: EpicFactions
main: com.gmail.justbru00.epicfactions.main.Main
version: 1.1
description: A plugin for ComputerFactions Server
author: Justin Brubaker

commands:
 epicfactions:
       description: Version and License command.     
 bottlexp:
       description: Gives the player a Xp bottle with some of the players levels.